### ISSUE TITLE
looking for help

### ISSUE THREAD

**Issue by yeralexey** [GraphGrailAi/ruGPT3-ZhirV#2]
really sory for bothering you here, but thre is no email or smth in your account, so decided to do it this way.

https://github.com/coleifer/vedis-python/issues/21

i found this on git, faciing the same trouble, did u solve it somehow? they say to check the docs, found nothing there, thanks

**Comment by GraphGrailAi** [comment]
Hi, i am not sure a remember an issue year ago, my guess it is a concurrency issue: when 2 or more users use database it become busy because 2 users try to write at the same time. This is the common issue for light dbs, best solution to switch to Postgres
